# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)



ocp_list = [
	"Desempleado",
	"Ingeniero",
	"Licenciado",
	"Docente",
	"Estudiante",
	"Comerciante",
	"Abogado",
	"Plomero",
	"Mecánico",
	"Electricista",
	"Matemático"
]

p "  -> Ocupations: Manufacturing"
ocp_list.each do |desc|
	Ocupation.create(description: desc)
end
p "  ->   -> Created #{Ocupation.count} Ocupations"

academic_lev_list = [
	"none",
	"Basic",
	"Bachelor",
	"College",
	"Magister",
	"Doctorate",
	"PHD"
]

p "  -> Academic Levels: Manufacturing"
academic_lev_list.each do |desc|
	AcademicLevel.create(description: desc)
end
p "  ->   -> Created #{AcademicLevel.count} Academic Levels"

relationship_list = [
	"none",
	"Padre/Madre",
	"Hermano/Hermana",
	"Primo/Prima",
	"Tío/Tía",
	"Abuelo/Abuela",
	"Tutor Legal"
]

p "  -> Relationships: Manufacturing"
relationship_list.each do |desc|
	Relationship.create(description: desc)
end
p "  ->   -> Created #{Relationship.count} Relationships"

document_type_list = [
	["Cédula Venezolana", "V-"],
	["Cédula Extranjera", "E-"],
	["Pasaporte", "P-"],
	["Persona Juridica", "J-"]
]

p "  -> Document Types: Manufacturing"
document_type_list.each do |desc, tk|
	DocumentType.create(description: desc, tok: tk)
end
p "  ->   -> Created #{DocumentType.count} Document Types"

nationality_list = [
	"VENEZOLANA",
	"NAMIBIANA",
	"ANGOLESA",
	"ARGELIANA",
	"DE BENNIN",
	"BOTSWANESA",
	"BURUNDESA",
	"DE CABO VERDE",
	"COMORENSE",
	"CONGOLESA",
	"MARFILEÑA",
	"CHADIANA",
	"DE DJIBOUTI",
	"EGIPCIA",
	"ETIOPE",
	"GABONESA",
	"GAMBIANA",
	"GHANATA",
	"GUINEA",
	"GUINEA",
	"GUINEA ECUATORIANA",
	"LIBIA",
	"KENIANA",
	"LESOTHENSE",
	"LIBERIANA",
	"MALAWIANA",
	"MALIENSE",
	"MARROQUI",
	"MAURICIANA",
	"MAURITANA",
	"MOZAMBIQUEÑA",
	"NIGERINA",
	"NIGERIANA",
	"CENTRO AFRICANA",
	"CAMERUNESA",
	"TANZANIANA",
	"RWANDESA",
	"DEL SAHARA",
	"DE SANTO TOME",
	"SENEGALESA",
	"DE SEYCHELLES",
	"SIERRA LEONESA",
	"SOMALI",
	"SUDAFRICANA",
	"SUDANESA",
	"SWAZI",
	"TOGOLESA",
	"TUNECINA",
	"UGANDESA",
	"ZAIRANA",
	"ZAMBIANA",
	"DE ZIMBAWI",
	"ARGENTINA",
	"BAHAMEÑA",
	"DE BARBADOS",
	"BELICEÑA",
	"BOLIVIANA",
	"BRASILEÑA",
	"CANADIENSE",
	"COLOMBIANA",
	"COSTARRICENSE",
	"CUBANA",
	"CHILENA",
	"DOMINICA",
	"SALVADOREÑA",
	"ESTADOUNIDENSE",
	"GRANADINA",
	"GUATEMALTECA",
	"BRITANICA",
	"GUYANESA",
	"HAITIANA",
	"HONDUREÑA",
	"JAMAIQUINA",
	"MEXICANA",
	"NICARAGUENSE",
	"PANAMEÑA",
	"PARAGUAYA",
	"PERUANA",
	"PUERTORRIQUEÑA",
	"DOMINICANA",
	"SANTA LUCIENSE",
	"SURINAMENSE",
	"TRINITARIA",
	"URUGUAYA",
	"VENEZOLANA",
	"AMERICANA",
	"AFGANA",
	"DE BAHREIN",
	"BHUTANESA",
	"BIRMANA",
	"NORCOREANA",
	"SUDCOREANA",
	"CHINA",
	"CHIPRIOTA",
	"ARABE",
	"FILIPINA",
	"HINDU",
	"INDONESA",
	"IRAQUI",
	"IRANI",
	"ISRAELI",
	"JAPONESA",
	"JORDANA",
	"CAMBOYANA",
	"KUWAITI",
	"LIBANESA",
	"MALASIA",
	"MALDIVA",
	"MONGOLESA",
	"NEPALESA",
	"OMANESA",
	"PAKISTANI",
	"DEL QATAR",
	"SIRIA",
	"LAOSIANA",
	"SINGAPORENSE",
	"TAILANDESA",
	"TAIWANESA",
	"TURCA",
	"NORVIETNAMITA",
	"YEMENI",
	"ALBANESA",
	"ALEMANA",
	"ANDORRANA",
	"AUSTRIACA",
	"BELGA",
	"BULGARA",
	"CHECOSLOVACA",
	"DANESA",
	"VATICANA",
	"ESPAÑOLA",
	"FINLANDESA",
	"FRANCESA",
	"GRIEGA",
	"HUNGARA",
	"IRLANDESA",
	"ISLANDESA",
	"ITALIANA",
	"LIECHTENSTENSE",
	"LUXEMBURGUESA",
	"MALTESA",
	"MONEGASCA",
	"NORUEGA",
	"HOLANDESA",
	"PORTUGUESA",
	"BRITANICA",
	"SOVIETICA BIELORRUSA",
	"SOVIETICA UCRANIANA",
	"RUMANA",
	"SAN MARINENSE",
	"SUECA",
	"SUIZA",
	"YUGOSLAVA",
	"AUSTRALIANA",
	"FIJIANA",
	"SALOMONESA",
	"NAURUANA",
	"PAPUENSE",
	"SAMOANA",
	"ESLOVACA",
	"BURKINA FASO",
	"ESTONIA",
	"MICRONECIA",
	"REINO UNIDO(DEPEN. TET. BRIT.)",
	"REINO UNIDO(BRIT. DEL EXT.)",
	"REINO UNIDO(C. BRIT. DEL EXT.)",
	"REINO UNIDO",
	"KIRGUISTAN",
	"LITUANIA ",
	"MOLDOVIA, REPUBLICA DE",
	"MACEDONIA",
	"ESLOVENIA",
	"ESLOVAQUIA"
]

p "  -> Nationalities: Manufacturing"
nationality_list.each do |desc|
	Nationality.create(description: desc)
end
p "  ->   -> Created #{Nationality.count} Nationalities"

state_list = [
	"Amazonas",
	"Anzoátegui",
	"Apure",
	"Aragua",
	"Barinas",
	"Bolívar",
	"Carabobo",
	"Cojedes",
	"Delta Amacuro",
	"Falcón",
	"Guárico",
	"Lara",
	"Mérida",
	"Miranda",
	"Monagas",
	"Nueva Esparta",
	"Portuguesa",
	"Sucre",
	"Táchira",
	"Trujillo",
	"Vargas",
	"Yaracuy",
	"Zulia",
	"Distrito Capital",
	"Dependencias Federales"
]

p "  -> States: Manufacturing"
state_list.each do |desc|
	State.create(description: desc)
end
p "  ->   -> Created #{State.count} States"

municipality_list = [
	[ 1, "Alto Orinoco" ],
	[ 1, "Atabapo" ],
	[ 1, "Atures" ],
	[ 1, "Autana" ],
	[ 1, "Manapiare" ],
	[ 1, "Maroa" ],
	[ 1, "Río Negro" ],
	[ 2, "Anaco" ],
	[ 2, "Aragua" ],
	[ 2, "Manuel Ezequiel Bruzual" ],
	[ 2, "Diego Bautista Urbaneja" ],
	[ 2, "Fernando Peñalver" ],
	[ 2, "Francisco Del Carmen Carvajal" ],
	[ 2, "General Sir Arthur McGregor" ],
	[ 2, "Guanta" ],
	[ 2, "Independencia" ],
	[ 2, "José Gregorio Monagas" ],
	[ 2, "Juan Antonio Sotillo" ],
	[ 2, "Juan Manuel Cajigal" ],
	[ 2, "Libertad" ],
	[ 2, "Francisco de Miranda" ],
	[ 2, "Pedro María Freites" ],
	[ 2, "Píritu" ],
	[ 2, "San José de Guanipa" ],
	[ 2, "San Juan de Capistrano" ],
	[ 2, "Santa Ana" ],
	[ 2, "Simón Bolívar" ],
	[ 2, "Simón Rodríguez" ],
	[ 3, "Achaguas" ],
	[ 3, "Biruaca" ],
	[ 3, "Muñóz" ],
	[ 3, "Páez" ],
	[ 3, "Pedro Camejo" ],
	[ 3, "Rómulo Gallegos" ],
	[ 3, "San Fernando" ],
	[ 4, "Atanasio Girardot" ],
	[ 4, "Bolívar" ],
	[ 4, "Camatagua" ],
	[ 4, "Francisco Linares Alcántara" ],
	[ 4, "José Ángel Lamas" ],
	[ 4, "José Félix Ribas" ],
	[ 4, "José Rafael Revenga" ],
	[ 4, "Libertador" ],
	[ 4, "Mario Briceño Iragorry" ],
	[ 4, "Ocumare de la Costa de Oro" ],
	[ 4, "San Casimiro" ],
	[ 4, "San Sebastián" ],
	[ 4, "Santiago Mariño" ],
	[ 4, "Santos Michelena" ],
	[ 4, "Sucre" ],
	[ 4, "Tovar" ],
	[ 4, "Urdaneta" ],
	[ 4, "Zamora" ],
	[ 5, "Alberto Arvelo Torrealba" ],
	[ 5, "Andrés Eloy Blanco" ],
	[ 5, "Antonio José de Sucre" ],
	[ 5, "Arismendi" ],
	[ 5, "Barinas" ],
	[ 5, "Bolívar" ],
	[ 5, "Cruz Paredes" ],
	[ 5, "Ezequiel Zamora" ],
	[ 5, "Obispos" ],
	[ 5, "Pedraza" ],
	[ 5, "Rojas" ],
	[ 5, "Sosa" ],
	[ 6, "Caroní" ],
	[ 6, "Cedeño" ],
	[ 6, "El Callao" ],
	[ 6, "Gran Sabana" ],
	[ 6, "Heres" ],
	[ 6, "Piar" ],
	[ 6, "Angostura (Raúl Leoni)" ],
	[ 6, "Roscio" ],
	[ 6, "Sifontes" ],
	[ 6, "Sucre" ],
	[ 6, "Padre Pedro Chien" ],
	[ 7, "Bejuma" ],
	[ 7, "Carlos Arvelo" ],
	[ 7, "Diego Ibarra" ],
	[ 7, "Guacara" ],
	[ 7, "Juan José Mora" ],
	[ 7, "Libertador" ],
	[ 7, "Los Guayos" ],
	[ 7, "Miranda" ],
	[ 7, "Montalbán" ],
	[ 7, "Naguanagua" ],
	[ 7, "Puerto Cabello" ],
	[ 7, "San Diego" ],
	[ 7, "San Joaquín" ],
	[ 7, "Valencia" ],
	[ 8, "Anzoátegui" ],
	[ 8, "Tinaquillo" ],
	[ 8, "Girardot" ],
	[ 8, "Lima Blanco" ],
	[ 8, "Pao de San Juan Bautista" ],
	[ 8, "Ricaurte" ],
	[ 8, "Rómulo Gallegos" ],
	[ 8, "San Carlos" ],
	[ 8, "Tinaco" ],
	[ 9, "Antonio Díaz" ],
	[ 9, "Casacoima" ],
	[ 9, "Pedernales" ],
	[ 9, "Tucupita" ],
	[ 10, "Acosta" ],
	[ 10, "Bolívar" ],
	[ 10, "Buchivacoa" ],
	[ 10, "Cacique Manaure" ],
	[ 10, "Carirubana" ],
	[ 10, "Colina" ],
	[ 10, "Dabajuro" ],
	[ 10, "Democracia" ],
	[ 10, "Falcón" ],
	[ 10, "Federación" ],
	[ 10, "Jacura" ],
	[ 10, "José Laurencio Silva" ],
	[ 10, "Los Taques" ],
	[ 10, "Mauroa" ],
	[ 10, "Miranda" ],
	[ 10, "Monseñor Iturriza" ],
	[ 10, "Palmasola" ],
	[ 10, "Petit" ],
	[ 10, "Píritu" ],
	[ 10, "San Francisco" ],
	[ 10, "Sucre" ],
	[ 10, "Tocópero" ],
	[ 10, "Unión" ],
	[ 10, "Urumaco" ],
	[ 10, "Zamora" ],
	[ 11, "Camaguán" ],
	[ 11, "Chaguaramas" ],
	[ 11, "El Socorro" ],
	[ 11, "José Félix Ribas" ],
	[ 11, "José Tadeo Monagas" ],
	[ 11, "Juan Germán Roscio" ],
	[ 11, "Julián Mellado" ],
	[ 11, "Las Mercedes" ],
	[ 11, "Leonardo Infante" ],
	[ 11, "Pedro Zaraza" ],
	[ 11, "Ortíz" ],
	[ 11, "San Gerónimo de Guayabal" ],
	[ 11, "San José de Guaribe" ],
	[ 11, "Santa María de Ipire" ],
	[ 11, "Sebastián Francisco de Miranda" ],
	[ 12, "Andrés Eloy Blanco" ],
	[ 12, "Crespo" ],
	[ 12, "Iribarren" ],
	[ 12, "Jiménez" ],
	[ 12, "Morán" ],
	[ 12, "Palavecino" ],
	[ 12, "Simón Planas" ],
	[ 12, "Torres" ],
	[ 12, "Urdaneta" ],
	[ 13, "Alberto Adriani" ],
	[ 13, "Andrés Bello" ],
	[ 13, "Antonio Pinto Salinas" ],
	[ 13, "Aricagua" ],
	[ 13, "Arzobispo Chacón" ],
	[ 13, "Campo Elías" ],
	[ 13, "Caracciolo Parra Olmedo" ],
	[ 13, "Cardenal Quintero" ],
	[ 13, "Guaraque" ],
	[ 13, "Julio César Salas" ],
	[ 13, "Justo Briceño" ],
	[ 13, "Libertador" ],
	[ 13, "Miranda" ],
	[ 13, "Obispo Ramos de Lora" ],
	[ 13, "Padre Noguera" ],
	[ 13, "Pueblo Llano" ],
	[ 13, "Rangel" ],
	[ 13, "Rivas Dávila" ],
	[ 13, "Santos Marquina" ],
	[ 13, "Sucre" ],
	[ 13, "Tovar" ],
	[ 13, "Tulio Febres Cordero" ],
	[ 13, "Zea" ],
	[ 14, "Acevedo" ],
	[ 14, "Andrés Bello" ],
	[ 14, "Baruta" ],
	[ 14, "Brión" ],
	[ 14, "Buroz" ],
	[ 14, "Carrizal" ],
	[ 14, "Chacao" ],
	[ 14, "Cristóbal Rojas" ],
	[ 14, "El Hatillo" ],
	[ 14, "Guaicaipuro" ],
	[ 14, "Independencia" ],
	[ 14, "Lander" ],
	[ 14, "Los Salias" ],
	[ 14, "Páez" ],
	[ 14, "Paz Castillo" ],
	[ 14, "Pedro Gual" ],
	[ 14, "Plaza" ],
	[ 14, "Simón Bolívar" ],
	[ 14, "Sucre" ],
	[ 14, "Urdaneta" ],
	[ 14, "Zamora" ],
	[ 15, "Acosta" ],
	[ 15, "Aguasay" ],
	[ 15, "Bolívar" ],
	[ 15, "Caripe" ],
	[ 15, "Cedeño" ],
	[ 15, "Ezequiel Zamora" ],
	[ 15, "Libertador" ],
	[ 15, "Maturín" ],
	[ 15, "Piar" ],
	[ 15, "Punceres" ],
	[ 15, "Santa Bárbara" ],
	[ 15, "Sotillo" ],
	[ 15, "Uracoa" ],
	[ 16, "Antolín del Campo" ],
	[ 16, "Arismendi" ],
	[ 16, "García" ],
	[ 16, "Gómez" ],
	[ 16, "Maneiro" ],
	[ 16, "Marcano" ],
	[ 16, "Mariño" ],
	[ 16, "Península de Macanao" ],
	[ 16, "Tubores" ],
	[ 16, "Villalba" ],
	[ 16, "Díaz" ],
	[ 17, "Agua Blanca" ],
	[ 17, "Araure" ],
	[ 17, "Esteller" ],
	[ 17, "Guanare" ],
	[ 17, "Guanarito" ],
	[ 17, "Monseñor José Vicente de Unda" ],
	[ 17, "Ospino" ],
	[ 17, "Páez" ],
	[ 17, "Papelón" ],
	[ 17, "San Genaro de Boconoíto" ],
	[ 17, "San Rafael de Onoto" ],
	[ 17, "Santa Rosalía" ],
	[ 17, "Sucre" ],
	[ 17, "Turén" ],
	[ 18, "Andrés Eloy Blanco" ],
	[ 18, "Andrés Mata" ],
	[ 18, "Arismendi" ],
	[ 18, "Benítez" ],
	[ 18, "Bermúdez" ],
	[ 18, "Bolívar" ],
	[ 18, "Cajigal" ],
	[ 18, "Cruz Salmerón Acosta" ],
	[ 18, "Libertador" ],
	[ 18, "Mariño" ],
	[ 18, "Mejía" ],
	[ 18, "Montes" ],
	[ 18, "Ribero" ],
	[ 18, "Sucre" ],
	[ 18, "Valdéz" ],
	[ 19, "Andrés Bello" ],
	[ 19, "Antonio Rómulo Costa" ],
	[ 19, "Ayacucho" ],
	[ 19, "Bolívar" ],
	[ 19, "Cárdenas" ],
	[ 19, "Córdoba" ],
	[ 19, "Fernández Feo" ],
	[ 19, "Francisco de Miranda" ],
	[ 19, "García de Hevia" ],
	[ 19, "Guásimos" ],
	[ 19, "Independencia" ],
	[ 19, "Jáuregui" ],
	[ 19, "José María Vargas" ],
	[ 19, "Junín" ],
	[ 19, "Libertad" ],
	[ 19, "Libertador" ],
	[ 19, "Lobatera" ],
	[ 19, "Michelena" ],
	[ 19, "Panamericano" ],
	[ 19, "Pedro María Ureña" ],
	[ 19, "Rafael Urdaneta" ],
	[ 19, "Samuel Darío Maldonado" ],
	[ 19, "San Cristóbal" ],
	[ 19, "Seboruco" ],
	[ 19, "Simón Rodríguez" ],
	[ 19, "Sucre" ],
	[ 19, "Torbes" ],
	[ 19, "Uribante" ],
	[ 19, "San Judas Tadeo" ],
	[ 20, "Andrés Bello" ],
	[ 20, "Boconó" ],
	[ 20, "Bolívar" ],
	[ 20, "Candelaria" ],
	[ 20, "Carache" ],
	[ 20, "Escuque" ],
	[ 20, "José Felipe Márquez Cañizalez" ],
	[ 20, "Juan Vicente Campos Elías" ],
	[ 20, "La Ceiba" ],
	[ 20, "Miranda" ],
	[ 20, "Monte Carmelo" ],
	[ 20, "Motatán" ],
	[ 20, "Pampán" ],
	[ 20, "Pampanito" ],
	[ 20, "Rafael Rangel" ],
	[ 20, "San Rafael de Carvajal" ],
	[ 20, "Sucre" ],
	[ 20, "Trujillo" ],
	[ 20, "Urdaneta" ],
	[ 20, "Valera" ],
	[ 21, "Vargas" ],
	[ 22, "Arístides Bastidas" ],
	[ 22, "Bolívar" ],
	[ 22, "Bruzual" ],
	[ 22, "Cocorote" ],
	[ 22, "Independencia" ],
	[ 22, "José Antonio Páez" ],
	[ 22, "La Trinidad" ],
	[ 22, "Manuel Monge" ],
	[ 22, "Nirgua" ],
	[ 22, "Peña" ],
	[ 22, "San Felipe" ],
	[ 22, "Sucre" ],
	[ 22, "Urachiche" ],
	[ 22, "José Joaquín Veroes" ],
	[ 23, "Almirante Padilla" ],
	[ 23, "Baralt" ],
	[ 23, "Cabimas" ],
	[ 23, "Catatumbo" ],
	[ 23, "Colón" ],
	[ 23, "Francisco Javier Pulgar" ],
	[ 23, "Páez" ],
	[ 23, "Jesús Enrique Losada" ],
	[ 23, "Jesús María Semprún" ],
	[ 23, "La Cañada de Urdaneta" ],
	[ 23, "Lagunillas" ],
	[ 23, "Machiques de Perijá" ],
	[ 23, "Mara" ],
	[ 23, "Maracaibo" ],
	[ 23, "Miranda" ],
	[ 23, "Rosario de Perijá" ],
	[ 23, "San Francisco" ],
	[ 23, "Santa Rita" ],
	[ 23, "Simón Bolívar" ],
	[ 23, "Sucre" ],
	[ 23, "Valmore Rodríguez" ],
	[ 24, "Libertador" ]
]

p "  -> Municipalities: Manufacturing"
municipality_list.each do |id,desc|
	Municipality.create(State_id: id, description: desc)
end
p "  ->   -> Created #{Municipality.count} Municipalities"

parish_list = [
	[ 1, "Alto Orinoco" ],
	[ 1, "Huachamacare Acanaña" ],
	[ 1, "Marawaka Toky Shamanaña" ],
	[ 1, "Mavaka Mavaka" ],
	[ 1, "Sierra Parima Parimabé" ],
	[ 2, "Ucata Laja Lisa" ],
	[ 2, "Yapacana Macuruco" ],
	[ 2, "Caname Guarinuma" ],
	[ 3, "Fernando Girón Tovar" ],
	[ 3, "Luis Alberto Gómez" ],
	[ 3, "Pahueña Limón de Parhueña" ],
	[ 3, "Platanillal Platanillal" ],
	[ 4, "Samariapo" ],
	[ 4, "Sipapo" ],
	[ 4, "Munduapo" ],
	[ 4, "Guayapo" ],
	[ 5, "Alto Ventuari" ],
	[ 5, "Medio Ventuari" ],
	[ 5, "Bajo Ventuari" ],
	[ 6, "Victorino" ],
	[ 6, "Comunidad" ],
	[ 7, "Casiquiare" ],
	[ 7, "Cocuy" ],
	[ 7, "San Carlos de Río Negro" ],
	[ 7, "Solano" ],
	[ 8, "Anaco" ],
	[ 8, "San Joaquín" ],
	[ 9, "Cachipo" ],
	[ 9, "Aragua de Barcelona" ],
	[ 11, "Lechería" ],
	[ 11, "El Morro" ],
	[ 12, "Puerto Píritu" ],
	[ 12, "San Miguel" ],
	[ 12, "Sucre" ],
	[ 13, "Valle de Guanape" ],
	[ 13, "Santa Bárbara" ],
	[ 14, "El Chaparro" ],
	[ 14, "Tomás Alfaro" ],
	[ 14, "Calatrava" ],
	[ 15, "Guanta" ],
	[ 15, "Chorrerón" ],
	[ 16, "Mamo" ],
	[ 16, "Soledad" ],
	[ 17, "Mapire" ],
	[ 17, "Piar" ],
	[ 17, "Santa Clara" ],
	[ 17, "San Diego de Cabrutica" ],
	[ 17, "Uverito" ],
	[ 17, "Zuata" ],
	[ 18, "Puerto La Cruz" ],
	[ 18, "Pozuelos" ],
	[ 19, "Onoto" ],
	[ 19, "San Pablo" ],
	[ 20, "San Mateo" ],
	[ 20, "El Carito" ],
	[ 20, "Santa Inés" ],
	[ 20, "La Romereña" ],
	[ 21, "Atapirire" ],
	[ 21, "Boca del Pao" ],
	[ 21, "El Pao" ],
	[ 21, "Pariaguán" ],
	[ 22, "Cantaura" ],
	[ 22, "Libertador" ],
	[ 22, "Santa Rosa" ],
	[ 22, "Urica" ],
	[ 23, "Píritu" ],
	[ 23, "San Francisco" ],
	[ 24, "San José de Guanipa" ],
	[ 25, "Boca de Uchire" ],
	[ 25, "Boca de Chávez" ],
	[ 26, "Pueblo Nuevo" ],
	[ 26, "Santa Ana" ],
	[ 27, "Bergantín" ],
	[ 27, "Caigua" ],
	[ 27, "El Carmen" ],
	[ 27, "El Pilar" ],
	[ 27, "Naricual" ],
	[ 27, "San Crsitóbal" ],
	[ 28, "Edmundo Barrios" ],
	[ 28, "Miguel Otero Silva" ],
	[ 29, "Achaguas" ],
	[ 29, "Apurito" ],
	[ 29, "El Yagual" ],
	[ 29, "Guachara" ],
	[ 29, "Mucuritas" ],
	[ 29, "Queseras del medio" ],
	[ 30, "Biruaca" ],
	[ 31, "Bruzual" ],
	[ 31, "Mantecal" ],
	[ 31, "Quintero" ],
	[ 31, "Rincón Hondo" ],
	[ 31, "San Vicente" ],
	[ 32, "Guasdualito" ],
	[ 32, "Aramendi" ],
	[ 32, "El Amparo" ],
	[ 32, "San Camilo" ],
	[ 32, "Urdaneta" ],
	[ 33, "San Juan de Payara" ],
	[ 33, "Codazzi" ],
	[ 33, "Cunaviche" ],
	[ 34, "Elorza" ],
	[ 34, "La Trinidad" ],
	[ 35, "San Fernando" ],
	[ 35, "El Recreo" ],
	[ 35, "Peñalver" ],
	[ 35, "San Rafael de Atamaica" ],
	[ 36, "Pedro José Ovalles" ],
	[ 36, "Joaquín Crespo" ],
	[ 36, "José Casanova Godoy" ],
	[ 36, "Madre María de San José" ],
	[ 36, "Andrés Eloy Blanco" ],
	[ 36, "Los Tacarigua" ],
	[ 36, "Las Delicias" ],
	[ 36, "Choroní" ],
	[ 37, "Bolívar" ],
	[ 38, "Camatagua" ],
	[ 38, "Carmen de Cura" ],
	[ 39, "Santa Rita" ],
	[ 39, "Francisco de Miranda" ],
	[ 39, "Moseñor Feliciano González" ],
	[ 40, "Santa Cruz" ],
	[ 41, "José Félix Ribas" ],
	[ 41, "Castor Nieves Ríos" ],
	[ 41, "Las Guacamayas" ],
	[ 41, "Pao de Zárate" ],
	[ 41, "Zuata" ],
	[ 42, "José Rafael Revenga" ],
	[ 43, "Palo Negro" ],
	[ 43, "San Martín de Porres" ],
	[ 44, "El Limón" ],
	[ 44, "Caña de Azúcar" ],
	[ 45, "Ocumare de la Costa" ],
	[ 46, "San Casimiro" ],
	[ 46, "Güiripa" ],
	[ 46, "Ollas de Caramacate" ],
	[ 46, "Valle Morín" ],
	[ 47, "San Sebastían" ],
	[ 48, "Turmero" ],
	[ 48, "Arevalo Aponte" ],
	[ 48, "Chuao" ],
	[ 48, "Samán de Güere" ],
	[ 48, "Alfredo Pacheco Miranda" ],
	[ 49, "Santos Michelena" ],
	[ 49, "Tiara" ],
	[ 50, "Cagua" ],
	[ 50, "Bella Vista" ],
	[ 51, "Tovar" ],
	[ 52, "Urdaneta" ],
	[ 52, "Las Peñitas" ],
	[ 52, "San Francisco de Cara" ],
	[ 52, "Taguay" ],
	[ 53, "Zamora" ],
	[ 53, "Magdaleno" ],
	[ 53, "San Francisco de Asís" ],
	[ 53, "Valles de Tucutunemo" ],
	[ 53, "Augusto Mijares" ],
	[ 54, "Sabaneta" ],
	[ 54, "Juan Antonio Rodríguez Domínguez" ],
	[ 55, "El Cantón" ],
	[ 55, "Santa Cruz de Guacas" ],
	[ 55, "Puerto Vivas" ],
	[ 56, "Ticoporo" ],
	[ 56, "Nicolás Pulido" ],
	[ 56, "Andrés Bello" ],
	[ 57, "Arismendi" ],
	[ 57, "Guadarrama" ],
	[ 57, "La Unión" ],
	[ 57, "San Antonio" ],
	[ 58, "Barinas" ],
	[ 58, "Alberto Arvelo Larriva" ],
	[ 58, "San Silvestre" ],
	[ 58, "Santa Inés" ],
	[ 58, "Santa Lucía" ],
	[ 58, "Torumos" ],
	[ 58, "El Carmen" ],
	[ 58, "Rómulo Betancourt" ],
	[ 58, "Corazón de Jesús" ],
	[ 58, "Ramón Ignacio Méndez" ],
	[ 58, "Alto Barinas" ],
	[ 58, "Manuel Palacio Fajardo" ],
	[ 58, "Juan Antonio Rodríguez Domínguez" ],
	[ 58, "Dominga Ortiz de Páez" ],
	[ 59, "Barinitas" ],
	[ 59, "Altamira de Cáceres" ],
	[ 59, "Calderas" ],
	[ 60, "Barrancas" ],
	[ 60, "El Socorro" ],
	[ 60, "Mazparrito" ],
	[ 61, "Santa Bárbara" ],
	[ 61, "Pedro Briceño Méndez" ],
	[ 61, "Ramón Ignacio Méndez" ],
	[ 61, "José Ignacio del Pumar" ],
	[ 62, "Obispos" ],
	[ 62, "Guasimitos" ],
	[ 62, "El Real" ],
	[ 62, "La Luz" ],
	[ 63, "Ciudad Bolívia" ],
	[ 63, "José Ignacio Briceño" ],
	[ 63, "José Félix Ribas" ],
	[ 63, "Páez" ],
	[ 64, "Libertad" ],
	[ 64, "Dolores" ],
	[ 64, "Santa Rosa" ],
	[ 64, "Palacio Fajardo" ],
	[ 65, "Ciudad de Nutrias" ],
	[ 65, "El Regalo" ],
	[ 65, "Puerto Nutrias" ],
	[ 65, "Santa Catalina" ],
	[ 66, "Cachamay" ],
	[ 66, "Chirica" ],
	[ 66, "Dalla Costa" ],
	[ 66, "Once de Abril" ],
	[ 66, "Simón Bolívar" ],
	[ 66, "Unare" ],
	[ 66, "Universidad" ],
	[ 66, "Vista al Sol" ],
	[ 66, "Pozo Verde" ],
	[ 66, "Yocoima" ],
	[ 66, "5 de Julio" ],
	[ 67, "Cedeño" ],
	[ 67, "Altagracia" ],
	[ 67, "Ascensión Farreras" ],
	[ 67, "Guaniamo" ],
	[ 67, "La Urbana" ],
	[ 67, "Pijiguaos" ],
	[ 68, "El Callao" ],
	[ 69, "Gran Sabana" ],
	[ 69, "Ikabarú" ],
	[ 70, "Catedral" ],
	[ 70, "Zea" ],
	[ 70, "Orinoco" ],
	[ 70, "José Antonio Páez" ],
	[ 70, "Marhuanta" ],
	[ 70, "Agua Salada" ],
	[ 70, "Vista Hermosa" ],
	[ 70, "La Sabanita" ],
	[ 70, "Panapana" ],
	[ 71, "Andrés Eloy Blanco" ],
	[ 71, "Pedro Cova" ],
	[ 72, "Raúl Leoni" ],
	[ 72, "Barceloneta" ],
	[ 72, "Santa Bárbara" ],
	[ 72, "San Francisco" ],
	[ 73, "Roscio" ],
	[ 73, "Salóm" ],
	[ 74, "Sifontes" ],
	[ 74, "Dalla Costa" ],
	[ 74, "San Isidro" ],
	[ 75, "Sucre" ],
	[ 75, "Aripao" ],
	[ 75, "Guarataro" ],
	[ 75, "Las Majadas" ],
	[ 75, "Moitaco" ],
	[ 76, "Padre Pedro Chien" ],
	[ 76, "Río Grande" ],
	[ 77, "Bejuma" ],
	[ 77, "Canoabo" ],
	[ 77, "Simón Bolívar" ],
	[ 78, "Güigüe" ],
	[ 78, "Carabobo" ],
	[ 78, "Tacarigua" ],
	[ 79, "Mariara" ],
	[ 79, "Aguas Calientes" ],
	[ 80, "Ciudad Alianza" ],
	[ 80, "Guacara" ],
	[ 80, "Yagua" ],
	[ 81, "Morón" ],
	[ 81, "Yagua" ],
	[ 82, "Tocuyito" ],
	[ 82, "Independencia" ],
	[ 83, "Los Guayos" ],
	[ 84, "Miranda" ],
	[ 85, "Montalbán" ],
	[ 86, "Naguanagua" ],
	[ 87, "Bartolomé Salóm" ],
	[ 87, "Democracia" ],
	[ 87, "Fraternidad" ],
	[ 87, "Goaigoaza" ],
	[ 87, "Juan José Flores" ],
	[ 87, "Unión" ],
	[ 87, "Borburata" ],
	[ 87, "Patanemo" ],
	[ 88, "San Diego" ],
	[ 89, "San Joaquín" ],
	[ 90, "Candelaria" ],
	[ 90, "Catedral" ],
	[ 90, "El Socorro" ],
	[ 90, "Miguel Peña" ],
	[ 90, "Rafael Urdaneta" ],
	[ 90, "San Blas" ],
	[ 90, "San José" ],
	[ 90, "Santa Rosa" ],
	[ 90, "Negro Primero" ],
	[ 91, "Cojedes" ],
	[ 91, "Juan de Mata Suárez" ],
	[ 92, "Tinaquillo" ],
	[ 93, "El Baúl" ],
	[ 93, "Sucre" ],
	[ 94, "La Aguadita" ],
	[ 94, "Macapo" ],
	[ 95, "El Pao" ],
	[ 96, "El Amparo" ],
	[ 96, "Libertad de Cojedes" ],
	[ 97, "Rómulo Gallegos" ],
	[ 98, "San Carlos de Austria" ],
	[ 98, "Juan Ángel Bravo" ],
	[ 98, "Manuel Manrique" ],
	[ 99, "General en Jefe José Laurencio Silva" ],
	[ 100, "Curiapo" ],
	[ 100, "Almirante Luis Brión" ],
	[ 100, "Francisco Aniceto Lugo" ],
	[ 100, "Manuel Renaud" ],
	[ 100, "Padre Barral" ],
	[ 100, "Santos de Abelgas" ],
	[ 101, "Imataca" ],
	[ 101, "Cinco de Julio" ],
	[ 101, "Juan Bautista Arismendi" ],
	[ 101, "Manuel Piar" ],
	[ 101, "Rómulo Gallegos" ],
	[ 102, "Pedernales" ],
	[ 102, "Luis Beltrán Prieto Figueroa" ],
	[ 103, "San José (Delta Amacuro)" ],
	[ 103, "José Vidal Marcano" ],
	[ 103, "Juan Millán" ],
	[ 103, "Leonardo Ruíz Pineda" ],
	[ 103, "Mariscal Antonio José de Sucre" ],
	[ 103, "Monseñor Argimiro García" ],
	[ 103, "San Rafael (Delta Amacuro)" ],
	[ 103, "Virgen del Valle" ],
	[ 10, "Clarines" ],
	[ 10, "Guanape" ],
	[ 10, "Sabana de Uchire" ],
	[ 104, "Capadare" ],
	[ 104, "La Pastora" ],
	[ 104, "Libertador" ],
	[ 104, "San Juan de los Cayos" ],
	[ 105, "Aracua" ],
	[ 105, "La Peña" ],
	[ 105, "San Luis" ],
	[ 106, "Bariro" ],
	[ 106, "Borojó" ],
	[ 106, "Capatárida" ],
	[ 106, "Guajiro" ],
	[ 106, "Seque" ],
	[ 106, "Zazárida" ],
	[ 106, "Valle de Eroa" ],
	[ 107, "Cacique Manaure" ],
	[ 108, "Norte" ],
	[ 108, "Carirubana" ],
	[ 108, "Santa Ana" ],
	[ 108, "Urbana Punta Cardón" ],
	[ 109, "La Vela de Coro" ],
	[ 109, "Acurigua" ],
	[ 109, "Guaibacoa" ],
	[ 109, "Las Calderas" ],
	[ 109, "Macoruca" ],
	[ 110, "Dabajuro" ],
	[ 111, "Agua Clara" ],
	[ 111, "Avaria" ],
	[ 111, "Pedregal" ],
	[ 111, "Piedra Grande" ],
	[ 111, "Purureche" ],
	[ 112, "Adaure" ],
	[ 112, "Adícora" ],
	[ 112, "Baraived" ],
	[ 112, "Buena Vista" ],
	[ 112, "Jadacaquiva" ],
	[ 112, "El Vínculo" ],
	[ 112, "El Hato" ],
	[ 112, "Moruy" ],
	[ 112, "Pueblo Nuevo" ],
	[ 113, "Agua Larga" ],
	[ 113, "El Paují" ],
	[ 113, "Independencia" ],
	[ 113, "Mapararí" ],
	[ 114, "Agua Linda" ],
	[ 114, "Araurima" ],
	[ 114, "Jacura" ],
	[ 115, "Tucacas" ],
	[ 115, "Boca de Aroa" ],
	[ 116, "Los Taques" ],
	[ 116, "Judibana" ],
	[ 117, "Mene de Mauroa" ],
	[ 117, "San Félix" ],
	[ 117, "Casigua" ],
	[ 118, "Guzmán Guillermo" ],
	[ 118, "Mitare" ],
	[ 118, "Río Seco" ],
	[ 118, "Sabaneta" ],
	[ 118, "San Antonio" ],
	[ 118, "San Gabriel" ],
	[ 118, "Santa Ana" ],
	[ 119, "Boca del Tocuyo" ],
	[ 119, "Chichiriviche" ],
	[ 119, "Tocuyo de la Costa" ],
	[ 120, "Palmasola" ],
	[ 121, "Cabure" ],
	[ 121, "Colina" ],
	[ 121, "Curimagua" ],
	[ 122, "San José de la Costa" ],
	[ 122, "Píritu" ],
	[ 123, "San Francisco" ],
	[ 124, "Sucre" ],
	[ 124, "Pecaya" ],
	[ 125, "Tocópero" ],
	[ 126, "El Charal" ],
	[ 126, "Las Vegas del Tuy" ],
	[ 126, "Santa Cruz de Bucaral" ],
	[ 127, "Bruzual" ],
	[ 127, "Urumaco" ],
	[ 128, "Puerto Cumarebo" ],
	[ 128, "La Ciénaga" ],
	[ 128, "La Soledad" ],
	[ 128, "Pueblo Cumarebo" ],
	[ 128, "Zazárida" ],
	[ 113, "Churuguara" ],
	[ 129, "Camaguán" ],
	[ 129, "Puerto Miranda" ],
	[ 129, "Uverito" ],
	[ 130, "Chaguaramas" ],
	[ 131, "El Socorro" ],
	[ 132, "Tucupido" ],
	[ 132, "San Rafael de Laya" ],
	[ 133, "Altagracia de Orituco" ],
	[ 133, "San Rafael de Orituco" ],
	[ 133, "San Francisco Javier de Lezama" ],
	[ 133, "Paso Real de Macaira" ],
	[ 133, "Carlos Soublette" ],
	[ 133, "San Francisco de Macaira" ],
	[ 133, "Libertad de Orituco" ],
	[ 134, "Cantaclaro" ],
	[ 134, "San Juan de los Morros" ],
	[ 134, "Parapara" ],
	[ 135, "El Sombrero" ],
	[ 135, "Sosa" ],
	[ 136, "Las Mercedes" ],
	[ 136, "Cabruta" ],
	[ 136, "Santa Rita de Manapire" ],
	[ 137, "Valle de la Pascua" ],
	[ 137, "Espino" ],
	[ 138, "San José de Unare" ],
	[ 138, "Zaraza" ],
	[ 139, "San José de Tiznados" ],
	[ 139, "San Francisco de Tiznados" ],
	[ 139, "San Lorenzo de Tiznados" ],
	[ 139, "Ortiz" ],
	[ 140, "Guayabal" ],
	[ 140, "Cazorla" ],
	[ 141, "San José de Guaribe" ],
	[ 141, "Uveral" ],
	[ 142, "Santa María de Ipire" ],
	[ 142, "Altamira" ],
	[ 143, "El Calvario" ],
	[ 143, "El Rastro" ],
	[ 143, "Guardatinajas" ],
	[ 143, "Capital Urbana Calabozo" ],
	[ 144, "Quebrada Honda de Guache" ],
	[ 144, "Pío Tamayo" ],
	[ 144, "Yacambú" ],
	[ 145, "Fréitez" ],
	[ 145, "José María Blanco" ],
	[ 146, "Catedral" ],
	[ 146, "Concepción" ],
	[ 146, "El Cují" ],
	[ 146, "Juan de Villegas" ],
	[ 146, "Santa Rosa" ],
	[ 146, "Tamaca" ],
	[ 146, "Unión" ],
	[ 146, "Aguedo Felipe Alvarado" ],
	[ 146, "Buena Vista" ],
	[ 146, "Juárez" ],
	[ 147, "Juan Bautista Rodríguez" ],
	[ 147, "Cuara" ],
	[ 147, "Diego de Lozada" ],
	[ 147, "Paraíso de San José" ],
	[ 147, "San Miguel" ],
	[ 147, "Tintorero" ],
	[ 147, "José Bernardo Dorante" ],
	[ 147, "Coronel Mariano Peraza " ],
	[ 148, "Bolívar" ],
	[ 148, "Anzoátegui" ],
	[ 148, "Guarico" ],
	[ 148, "Hilario Luna y Luna" ],
	[ 148, "Humocaro Alto" ],
	[ 148, "Humocaro Bajo" ],
	[ 148, "La Candelaria" ],
	[ 148, "Morán" ],
	[ 149, "Cabudare" ],
	[ 149, "José Gregorio Bastidas" ],
	[ 149, "Agua Viva" ],
	[ 150, "Sarare" ],
	[ 150, "Buría" ],
	[ 150, "Gustavo Vegas León" ],
	[ 151, "Trinidad Samuel" ],
	[ 151, "Antonio Díaz" ],
	[ 151, "Camacaro" ],
	[ 151, "Castañeda" ],
	[ 151, "Cecilio Zubillaga" ],
	[ 151, "Chiquinquirá" ],
	[ 151, "El Blanco" ],
	[ 151, "Espinoza de los Monteros" ],
	[ 151, "Lara" ],
	[ 151, "Las Mercedes" ],
	[ 151, "Manuel Morillo" ],
	[ 151, "Montaña Verde" ],
	[ 151, "Montes de Oca" ],
	[ 151, "Torres" ],
	[ 151, "Heriberto Arroyo" ],
	[ 151, "Reyes Vargas" ],
	[ 151, "Altagracia" ],
	[ 152, "Siquisique" ],
	[ 152, "Moroturo" ],
	[ 152, "San Miguel" ],
	[ 152, "Xaguas" ],
	[ 179, "Presidente Betancourt" ],
	[ 179, "Presidente Páez" ],
	[ 179, "Presidente Rómulo Gallegos" ],
	[ 179, "Gabriel Picón González" ],
	[ 179, "Héctor Amable Mora" ],
	[ 179, "José Nucete Sardi" ],
	[ 179, "Pulido Méndez" ],
	[ 180, "La Azulita" ],
	[ 181, "Santa Cruz de Mora" ],
	[ 181, "Mesa Bolívar" ],
	[ 181, "Mesa de Las Palmas" ],
	[ 182, "Aricagua" ],
	[ 182, "San Antonio" ],
	[ 183, "Canagua" ],
	[ 183, "Capurí" ],
	[ 183, "Chacantá" ],
	[ 183, "El Molino" ],
	[ 183, "Guaimaral" ],
	[ 183, "Mucutuy" ],
	[ 183, "Mucuchachí" ],
	[ 184, "Fernández Peña" ],
	[ 184, "Matriz" ],
	[ 184, "Montalbán" ],
	[ 184, "Acequias" ],
	[ 184, "Jají" ],
	[ 184, "La Mesa" ],
	[ 184, "San José del Sur" ],
	[ 185, "Tucaní" ],
	[ 185, "Florencio Ramírez" ],
	[ 186, "Santo Domingo" ],
	[ 186, "Las Piedras" ],
	[ 187, "Guaraque" ],
	[ 187, "Mesa de Quintero" ],
	[ 187, "Río Negro" ],
	[ 188, "Arapuey" ],
	[ 188, "Palmira" ],
	[ 189, "San Cristóbal de Torondoy" ],
	[ 189, "Torondoy" ],
	[ 190, "Antonio Spinetti Dini" ],
	[ 190, "Arias" ],
	[ 190, "Caracciolo Parra Pérez" ],
	[ 190, "Domingo Peña" ],
	[ 190, "El Llano" ],
	[ 190, "Gonzalo Picón Febres" ],
	[ 190, "Jacinto Plaza" ],
	[ 190, "Juan Rodríguez Suárez" ],
	[ 190, "Lasso de la Vega" ],
	[ 190, "Mariano Picón Salas" ],
	[ 190, "Milla" ],
	[ 190, "Osuna Rodríguez" ],
	[ 190, "Sagrario" ],
	[ 190, "El Morro" ],
	[ 190, "Los Nevados" ],
	[ 191, "Andrés Eloy Blanco" ],
	[ 191, "La Venta" ],
	[ 191, "Piñango" ],
	[ 191, "Timotes" ],
	[ 192, "Eloy Paredes" ],
	[ 192, "San Rafael de Alcázar" ],
	[ 192, "Santa Elena de Arenales" ],
	[ 193, "Santa María de Caparo" ],
	[ 194, "Pueblo Llano" ],
	[ 195, "Cacute" ],
	[ 195, "La Toma" ],
	[ 195, "Mucuchíes" ],
	[ 195, "Mucurubá" ],
	[ 195, "San Rafael" ],
	[ 196, "Gerónimo Maldonado" ],
	[ 196, "Bailadores" ],
	[ 197, "Tabay" ],
	[ 198, "Chiguará" ],
	[ 198, "Estánquez" ],
	[ 198, "Lagunillas" ],
	[ 198, "La Trampa" ],
	[ 198, "Pueblo Nuevo del Sur" ],
	[ 198, "San Juan" ],
	[ 199, "El Amparo" ],
	[ 199, "El Llano" ],
	[ 199, "San Francisco" ],
	[ 199, "Tovar" ],
	[ 200, "Independencia" ],
	[ 200, "María de la Concepción Palacios Blanco" ],
	[ 200, "Nueva Bolivia" ],
	[ 200, "Santa Apolonia" ],
	[ 201, "Caño El Tigre" ],
	[ 201, "Zea" ],
	[ 223, "Aragüita" ],
	[ 223, "Arévalo González" ],
	[ 223, "Capaya" ],
	[ 223, "Caucagua" ],
	[ 223, "Panaquire" ],
	[ 223, "Ribas" ],
	[ 223, "El Café" ],
	[ 223, "Marizapa" ],
	[ 224, "Cumbo" ],
	[ 224, "San José de Barlovento" ],
	[ 225, "El Cafetal" ],
	[ 225, "Las Minas" ],
	[ 225, "Nuestra Señora del Rosario" ],
	[ 226, "Higuerote" ],
	[ 226, "Curiepe" ],
	[ 226, "Tacarigua de Brión" ],
	[ 227, "Mamporal" ],
	[ 228, "Carrizal" ],
	[ 229, "Chacao" ],
	[ 230, "Charallave" ],
	[ 230, "Las Brisas" ],
	[ 231, "El Hatillo" ],
	[ 232, "Altagracia de la Montaña" ],
	[ 232, "Cecilio Acosta" ],
	[ 232, "Los Teques" ],
	[ 232, "El Jarillo" ],
	[ 232, "San Pedro" ],
	[ 232, "Tácata" ],
	[ 232, "Paracotos" ],
	[ 233, "Cartanal" ],
	[ 233, "Santa Teresa del Tuy" ],
	[ 234, "La Democracia" ],
	[ 234, "Ocumare del Tuy" ],
	[ 234, "Santa Bárbara" ],
	[ 235, "San Antonio de los Altos" ],
	[ 236, "Río Chico" ],
	[ 236, "El Guapo" ],
	[ 236, "Tacarigua de la Laguna" ],
	[ 236, "Paparo" ],
	[ 236, "San Fernando del Guapo" ],
	[ 237, "Santa Lucía del Tuy" ],
	[ 238, "Cúpira" ],
	[ 238, "Machurucuto" ],
	[ 239, "Guarenas" ],
	[ 240, "San Antonio de Yare" ],
	[ 240, "San Francisco de Yare" ],
	[ 241, "Leoncio Martínez" ],
	[ 241, "Petare" ],
	[ 241, "Caucagüita" ],
	[ 241, "Filas de Mariche" ],
	[ 241, "La Dolorita" ],
	[ 242, "Cúa" ],
	[ 242, "Nueva Cúa" ],
	[ 243, "Guatire" ],
	[ 243, "Bolívar" ],
	[ 258, "San Antonio de Maturín" ],
	[ 258, "San Francisco de Maturín" ],
	[ 259, "Aguasay" ],
	[ 260, "Caripito" ],
	[ 261, "El Guácharo" ],
	[ 261, "La Guanota" ],
	[ 261, "Sabana de Piedra" ],
	[ 261, "San Agustín" ],
	[ 261, "Teresen" ],
	[ 261, "Caripe" ],
	[ 262, "Areo" ],
	[ 262, "Capital Cedeño" ],
	[ 262, "San Félix de Cantalicio" ],
	[ 262, "Viento Fresco" ],
	[ 263, "El Tejero" ],
	[ 263, "Punta de Mata" ],
	[ 264, "Chaguaramas" ],
	[ 264, "Las Alhuacas" ],
	[ 264, "Tabasca" ],
	[ 264, "Temblador" ],
	[ 265, "Alto de los Godos" ],
	[ 265, "Boquerón" ],
	[ 265, "Las Cocuizas" ],
	[ 265, "La Cruz" ],
	[ 265, "San Simón" ],
	[ 265, "El Corozo" ],
	[ 265, "El Furrial" ],
	[ 265, "Jusepín" ],
	[ 265, "La Pica" ],
	[ 265, "San Vicente" ],
	[ 266, "Aparicio" ],
	[ 266, "Aragua de Maturín" ],
	[ 266, "Chaguamal" ],
	[ 266, "El Pinto" ],
	[ 266, "Guanaguana" ],
	[ 266, "La Toscana" ],
	[ 266, "Taguaya" ],
	[ 267, "Cachipo" ],
	[ 267, "Quiriquire" ],
	[ 268, "Santa Bárbara" ],
	[ 269, "Barrancas" ],
	[ 269, "Los Barrancos de Fajardo" ],
	[ 270, "Uracoa" ],
	[ 271, "Antolín del Campo" ],
	[ 373, "Bolivia" ],
	[ 373, "Carrillo" ],
	[ 373, "Cegarra" ],
	[ 373, "Chejendé" ],
	[ 373, "Manuel Salvador Ulloa" ],
	[ 373, "San José" ],
	[ 374, "Carache" ],
	[ 374, "La Concepción" ],
	[ 374, "Cuicas" ],
	[ 374, "Panamericana" ],
	[ 374, "Santa Cruz" ],
	[ 375, "Escuque" ],
	[ 375, "La Unión" ],
	[ 375, "Santa Rita" ],
	[ 375, "Sabana Libre" ],
	[ 376, "El Socorro" ],
	[ 376, "Los Caprichos" ],
	[ 376, "Antonio José de Sucre" ],
	[ 377, "Campo Elías" ],
	[ 377, "Arnoldo Gabaldón" ],
	[ 378, "Santa Apolonia" ],
	[ 378, "El Progreso" ],
	[ 378, "La Ceiba" ],
	[ 378, "Tres de Febrero" ],
	[ 379, "El Dividive" ],
	[ 379, "Agua Santa" ],
	[ 379, "Agua Caliente" ],
	[ 379, "El Cenizo" ],
	[ 379, "Valerita" ],
	[ 380, "Monte Carmelo" ],
	[ 380, "Buena Vista" ],
	[ 380, "Santa María del Horcón" ],
	[ 381, "Motatán" ],
	[ 381, "El Baño" ],
	[ 381, "Jalisco" ],
	[ 382, "Pampán" ],
	[ 382, "Flor de Patria" ],
	[ 382, "La Paz" ],
	[ 382, "Santa Ana" ],
	[ 383, "Pampanito" ],
	[ 383, "La Concepción" ],
	[ 383, "Pampanito II" ],
	[ 384, "Betijoque" ],
	[ 384, "José Gregorio Hernández" ],
	[ 384, "La Pueblita" ],
	[ 384, "Los Cedros" ],
	[ 385, "Carvajal" ],
	[ 385, "Campo Alegre" ],
	[ 385, "Antonio Nicolás Briceño" ],
	[ 385, "José Leonardo Suárez" ],
	[ 386, "Sabana de Mendoza" ],
	[ 386, "Junín" ],
	[ 386, "Valmore Rodríguez" ],
	[ 386, "El Paraíso" ],
	[ 387, "Andrés Linares" ],
	[ 387, "Chiquinquirá" ],
	[ 387, "Cristóbal Mendoza" ],
	[ 387, "Cruz Carrillo" ],
	[ 387, "Matriz" ],
	[ 387, "Monseñor Carrillo" ],
	[ 387, "Tres Esquinas" ],
	[ 388, "Cabimbú" ],
	[ 388, "Jajó" ],
	[ 388, "La Mesa de Esnujaque" ],
	[ 388, "Santiago" ],
	[ 388, "Tuñame" ],
	[ 388, "La Quebrada" ],
	[ 389, "Juan Ignacio Montilla" ],
	[ 389, "La Beatriz" ],
	[ 389, "La Puerta" ],
	[ 389, "Mendoza del Valle de Momboy" ],
	[ 389, "Mercedes Díaz" ],
	[ 389, "San Luis" ],
	[ 390, "Caraballeda" ],
	[ 390, "Carayaca" ],
	[ 390, "Carlos Soublette" ],
	[ 390, "Caruao Chuspa" ],
	[ 390, "Catia La Mar" ],
	[ 390, "El Junko" ],
	[ 390, "La Guaira" ],
	[ 390, "Macuto" ],
	[ 390, "Maiquetía" ],
	[ 390, "Naiguatá" ],
	[ 390, "Urimare" ],
	[ 391, "Arístides Bastidas" ],
	[ 392, "Bolívar" ],
	[ 407, "Chivacoa" ],
	[ 407, "Campo Elías" ],
	[ 408, "Cocorote" ],
	[ 409, "Independencia" ],
	[ 410, "José Antonio Páez" ],
	[ 411, "La Trinidad" ],
	[ 412, "Manuel Monge" ],
	[ 413, "Salóm" ],
	[ 413, "Temerla" ],
	[ 413, "Nirgua" ],
	[ 414, "San Andrés" ],
	[ 414, "Yaritagua" ],
	[ 415, "San Javier" ],
	[ 415, "Albarico" ],
	[ 415, "San Felipe" ],
	[ 416, "Sucre" ],
	[ 417, "Urachiche" ],
	[ 418, "El Guayabo" ],
	[ 418, "Farriar" ],
	[ 441, "Isla de Toas" ],
	[ 441, "Monagas" ],
	[ 442, "San Timoteo" ],
	[ 442, "General Urdaneta" ],
	[ 442, "Libertador" ],
	[ 442, "Marcelino Briceño" ],
	[ 442, "Pueblo Nuevo" ],
	[ 442, "Manuel Guanipa Matos" ],
	[ 443, "Ambrosio" ],
	[ 443, "Carmen Herrera" ],
	[ 443, "La Rosa" ],
	[ 443, "Germán Ríos Linares" ],
	[ 443, "San Benito" ],
	[ 443, "Rómulo Betancourt" ],
	[ 443, "Jorge Hernández" ],
	[ 443, "Punta Gorda" ],
	[ 443, "Arístides Calvani" ],
	[ 444, "Encontrados" ],
	[ 444, "Udón Pérez" ],
	[ 445, "Moralito" ],
	[ 445, "San Carlos del Zulia" ],
	[ 445, "Santa Cruz del Zulia" ],
	[ 445, "Santa Bárbara" ],
	[ 445, "Urribarrí" ],
	[ 446, "Carlos Quevedo" ],
	[ 446, "Francisco Javier Pulgar" ],
	[ 446, "Simón Rodríguez" ],
	[ 446, "Guamo-Gavilanes" ],
	[ 448, "La Concepción" ],
	[ 448, "San José" ],
	[ 448, "Mariano Parra León" ],
	[ 448, "José Ramón Yépez" ],
	[ 449, "Jesús María Semprún" ],
	[ 449, "Barí" ],
	[ 450, "Concepción" ],
	[ 450, "Andrés Bello" ],
	[ 450, "Chiquinquirá" ],
	[ 450, "El Carmelo" ],
	[ 450, "Potreritos" ],
	[ 451, "Libertad" ],
	[ 451, "Alonso de Ojeda" ],
	[ 451, "Venezuela" ],
	[ 451, "Eleazar López Contreras" ],
	[ 451, "Campo Lara" ],
	[ 452, "Bartolomé de las Casas" ],
	[ 452, "Libertad" ],
	[ 452, "Río Negro" ],
	[ 452, "San José de Perijá" ],
	[ 453, "San Rafael" ],
	[ 453, "La Sierrita" ],
	[ 453, "Las Parcelas" ],
	[ 453, "Luis de Vicente" ],
	[ 453, "Monseñor Marcos Sergio Godoy" ],
	[ 453, "Ricaurte" ],
	[ 453, "Tamare" ],
	[ 454, "Antonio Borjas Romero" ],
	[ 454, "Bolívar" ],
	[ 454, "Cacique Mara" ],
	[ 454, "Carracciolo Parra Pérez" ],
	[ 454, "Cecilio Acosta" ],
	[ 454, "Cristo de Aranza" ],
	[ 454, "Coquivacoa" ],
	[ 454, "Chiquinquirá" ],
	[ 454, "Francisco Eugenio Bustamante" ],
	[ 454, "Idelfonzo Vásquez" ],
	[ 454, "Juana de Ávila" ],
	[ 454, "Luis Hurtado Higuera" ],
	[ 454, "Manuel Dagnino" ],
	[ 454, "Olegario Villalobos" ],
	[ 454, "Raúl Leoni" ],
	[ 454, "Santa Lucía" ],
	[ 454, "Venancio Pulgar" ],
	[ 454, "San Isidro" ],
	[ 455, "Altagracia" ],
	[ 455, "Faría" ],
	[ 455, "Ana María Campos" ],
	[ 455, "San Antonio" ],
	[ 455, "San José" ],
	[ 456, "Donaldo García" ],
	[ 456, "El Rosario" ],
	[ 456, "Sixto Zambrano" ],
	[ 457, "San Francisco" ],
	[ 457, "El Bajo" ],
	[ 457, "Domitila Flores" ],
	[ 457, "Francisco Ochoa" ],
	[ 457, "Los Cortijos" ],
	[ 457, "Marcial Hernández" ],
	[ 458, "Santa Rita" ],
	[ 458, "El Mene" ],
	[ 458, "Pedro Lucas Urribarrí" ],
	[ 458, "José Cenobio Urribarrí" ],
	[ 459, "Rafael Maria Baralt" ],
	[ 459, "Manuel Manrique" ],
	[ 459, "Rafael Urdaneta" ],
	[ 460, "Bobures" ],
	[ 460, "Gibraltar" ],
	[ 460, "Heras" ],
	[ 460, "Monseñor Arturo Álvarez" ],
	[ 460, "Rómulo Gallegos" ],
	[ 460, "El Batey" ],
	[ 461, "Rafael Urdaneta" ],
	[ 461, "La Victoria" ],
	[ 461, "Raúl Cuenca" ],
	[ 447, "Sinamaica" ],
	[ 447, "Alta Guajira" ],
	[ 447, "Elías Sánchez Rubio" ],
	[ 447, "Guajira" ],
	[ 24, "Altagracia" ],
	[ 24, "Antímano" ],
	[ 24, "Caricuao" ],
	[ 24, "Catedral" ],
	[ 24, "Coche" ],
	[ 24, "El Junquito" ],
	[ 24, "El Paraíso" ],
	[ 24, "El Recreo" ],
	[ 24, "El Valle" ],
	[ 24, "La Candelaria" ],
	[ 24, "La Pastora" ],
	[ 24, "La Vega" ],
	[ 24, "Macarao" ],
	[ 24, "San Agustín" ],
	[ 24, "San Bernardino" ],
	[ 24, "San José" ],
	[ 24, "San Juan" ],
	[ 24, "San Pedro" ],
	[ 24, "Santa Rosalía" ],
	[ 24, "Santa Teresa" ],
	[ 24, "Sucre (Catia)" ],
	[ 24, "23 de enero" ],
	[ 272, "Arismendi" ],
	[ 273, "García" ],
	[ 273, "Francisco Fajardo" ],
	[ 274, "Bolívar" ],
	[ 274, "Guevara" ],
	[ 274, "Matasiete" ],
	[ 274, "Santa Ana" ],
	[ 274, "Sucre" ],
	[ 275, "Aguirre" ],
	[ 275, "Maneiro" ],
	[ 276, "Adrián" ],
	[ 276, "Juan Griego" ],
	[ 276, "Yaguaraparo" ],
	[ 277, "Porlamar" ],
	[ 278, "San Francisco de Macanao" ],
	[ 278, "Boca de Río" ],
	[ 279, "Tubores" ],
	[ 279, "Los Baleales" ],
	[ 280, "Vicente Fuentes" ],
	[ 280, "Villalba" ],
	[ 281, "San Juan Bautista" ],
	[ 281, "Zabala" ],
	[ 283, "Capital Araure" ],
	[ 283, "Río Acarigua" ],
	[ 284, "Capital Esteller" ],
	[ 284, "Uveral" ],
	[ 285, "Guanare" ],
	[ 285, "Córdoba" ],
	[ 285, "San José de la Montaña" ],
	[ 285, "San Juan de Guanaguanare" ],
	[ 285, "Virgen de la Coromoto" ],
	[ 286, "Guanarito" ],
	[ 286, "Trinidad de la Capilla" ],
	[ 286, "Divina Pastora" ],
	[ 287, "Monseñor José Vicente de Unda" ],
	[ 287, "Peña Blanca" ],
	[ 288, "Capital Ospino" ],
	[ 288, "Aparición" ],
	[ 288, "La Estación" ],
	[ 289, "Páez" ],
	[ 289, "Payara" ],
	[ 289, "Pimpinela" ],
	[ 289, "Ramón Peraza" ],
	[ 290, "Papelón" ],
	[ 290, "Caño Delgadito" ],
	[ 291, "San Genaro de Boconoito" ],
	[ 291, "Antolín Tovar" ],
	[ 292, "San Rafael de Onoto" ],
	[ 292, "Santa Fe" ],
	[ 292, "Thermo Morles" ],
	[ 293, "Santa Rosalía" ],
	[ 293, "Florida" ],
	[ 294, "Sucre" ],
	[ 294, "Concepción" ],
	[ 294, "San Rafael de Palo Alzado" ],
	[ 294, "Uvencio Antonio Velásquez" ],
	[ 294, "San José de Saguaz" ],
	[ 294, "Villa Rosa" ],
	[ 295, "Turén" ],
	[ 295, "Canelones" ],
	[ 295, "Santa Cruz" ],
	[ 295, "San Isidro Labrador" ],
	[ 296, "Mariño" ],
	[ 296, "Rómulo Gallegos" ],
	[ 297, "San José de Aerocuar" ],
	[ 297, "Tavera Acosta" ],
	[ 298, "Río Caribe" ],
	[ 298, "Antonio José de Sucre" ],
	[ 298, "El Morro de Puerto Santo" ],
	[ 298, "Puerto Santo" ],
	[ 298, "San Juan de las Galdonas" ],
	[ 299, "El Pilar" ],
	[ 299, "El Rincón" ],
	[ 299, "General Francisco Antonio Váquez" ],
	[ 299, "Guaraúnos" ],
	[ 299, "Tunapuicito" ],
	[ 299, "Unión" ],
	[ 300, "Santa Catalina" ],
	[ 300, "Santa Rosa" ],
	[ 300, "Santa Teresa" ],
	[ 300, "Bolívar" ],
	[ 300, "Maracapana" ],
	[ 302, "Libertad" ],
	[ 302, "El Paujil" ],
	[ 302, "Yaguaraparo" ],
	[ 303, "Cruz Salmerón Acosta" ],
	[ 303, "Chacopata" ],
	[ 303, "Manicuare" ],
	[ 304, "Tunapuy" ],
	[ 304, "Campo Elías" ],
	[ 305, "Irapa" ],
	[ 305, "Campo Claro" ],
	[ 305, "Maraval" ],
	[ 305, "San Antonio de Irapa" ],
	[ 305, "Soro" ],
	[ 306, "Mejía" ],
	[ 307, "Cumanacoa" ],
	[ 307, "Arenas" ],
	[ 307, "Aricagua" ],
	[ 307, "Cogollar" ],
	[ 307, "San Fernando" ],
	[ 307, "San Lorenzo" ],
	[ 308, "Villa Frontado (Muelle de Cariaco)" ],
	[ 308, "Catuaro" ],
	[ 308, "Rendón" ],
	[ 308, "San Cruz" ],
	[ 308, "Santa María" ],
	[ 309, "Altagracia" ],
	[ 309, "Santa Inés" ],
	[ 309, "Valentín Valiente" ],
	[ 309, "Ayacucho" ],
	[ 309, "San Juan" ],
	[ 309, "Raúl Leoni" ],
	[ 309, "Gran Mariscal" ],
	[ 310, "Cristóbal Colón" ],
	[ 310, "Bideau" ],
	[ 310, "Punta de Piedras" ],
	[ 310, "Güiria" ],
	[ 341, "Andrés Bello" ],
	[ 342, "Antonio Rómulo Costa" ],
	[ 343, "Ayacucho" ],
	[ 343, "Rivas Berti" ],
	[ 343, "San Pedro del Río" ],
	[ 344, "Bolívar" ],
	[ 344, "Palotal" ],
	[ 344, "General Juan Vicente Gómez" ],
	[ 344, "Isaías Medina Angarita" ],
	[ 345, "Cárdenas" ],
	[ 345, "Amenodoro Ángel Lamus" ],
	[ 345, "La Florida" ],
	[ 346, "Córdoba" ],
	[ 347, "Fernández Feo" ],
	[ 347, "Alberto Adriani" ],
	[ 347, "Santo Domingo" ],
	[ 348, "Francisco de Miranda" ],
	[ 349, "García de Hevia" ],
	[ 349, "Boca de Grita" ],
	[ 349, "José Antonio Páez" ],
	[ 350, "Guásimos" ],
	[ 351, "Independencia" ],
	[ 351, "Juan Germán Roscio" ],
	[ 351, "Román Cárdenas" ],
	[ 352, "Jáuregui" ],
	[ 352, "Emilio Constantino Guerrero" ],
	[ 352, "Monseñor Miguel Antonio Salas" ],
	[ 353, "José María Vargas" ],
	[ 354, "Junín" ],
	[ 354, "La Petrólea" ],
	[ 354, "Quinimarí" ],
	[ 354, "Bramón" ],
	[ 355, "Libertad" ],
	[ 355, "Cipriano Castro" ],
	[ 355, "Manuel Felipe Rugeles" ],
	[ 356, "Libertador" ],
	[ 356, "Doradas" ],
	[ 356, "Emeterio Ochoa" ],
	[ 356, "San Joaquín de Navay" ],
	[ 357, "Lobatera" ],
	[ 357, "Constitución" ],
	[ 358, "Michelena" ],
	[ 359, "Panamericano" ],
	[ 359, "La Palmita" ],
	[ 360, "Pedro María Ureña" ],
	[ 360, "Nueva Arcadia" ],
	[ 361, "Delicias" ],
	[ 361, "Pecaya" ],
	[ 362, "Samuel Darío Maldonado" ],
	[ 362, "Boconó" ],
	[ 362, "Hernández" ],
	[ 363, "La Concordia" ],
	[ 363, "San Juan Bautista" ],
	[ 363, "Pedro María Morantes" ],
	[ 363, "San Sebastián" ],
	[ 363, "Dr. Francisco Romero Lobo" ],
	[ 364, "Seboruco" ],
	[ 365, "Simón Rodríguez" ],
	[ 366, "Sucre" ],
	[ 366, "Eleazar López Contreras" ],
	[ 366, "San Pablo" ],
	[ 367, "Torbes" ],
	[ 368, "Uribante" ],
	[ 368, "Cárdenas" ],
	[ 368, "Juan Pablo Peñalosa" ],
	[ 368, "Potosí" ],
	[ 369, "San Judas Tadeo" ],
	[ 370, "Araguaney" ],
	[ 370, "El Jaguito" ],
	[ 370, "La Esperanza" ],
	[ 370, "Santa Isabel" ],
	[ 371, "Boconó" ],
	[ 371, "El Carmen" ],
	[ 371, "Mosquey" ],
	[ 371, "Ayacucho" ],
	[ 371, "Burbusay" ],
	[ 371, "General Ribas" ],
	[ 371, "Guaramacal" ],
	[ 371, "Vega de Guaramacal" ],
	[ 371, "Monseñor Jáuregui" ],
	[ 371, "Rafael Rangel" ],
	[ 371, "San Miguel" ],
	[ 371, "San José" ],
	[ 372, "Sabana Grande" ],
	[ 372, "Cheregüé" ],
	[ 372, "Granados" ],
	[ 373, "Arnoldo Gabaldón" ]
]

p "  -> Parishes: Manufacturing"
parish_list.each do |id, desc|
	Parish.create(Municipality_id: id,description: desc)
end
p "  ->   -> Created #{Parish.count} Parishes"

structure_lev_list = [
	"Grupo",
	"Distrito",
	"Región (Nac)",
	"Nacional",
	"superuser",
]

p "  -> Structure Levels: Manufacturing"
structure_lev_list.each do |desc|
	StructureLevel.create(description: desc)
end
p "  ->   -> Created #{StructureLevel.count} Structure Levels"

charges_list = [
	["Adulto Colaborador", 1],
	["Jefe De Manada Masculina", 1],
	["Sub Jefe De Manada Masculina", 1],
	["Jefe De Manada Femenina", 1],
	["Sub Jefe De Manada Femenina", 1],
	["Jefe De Tropa Masculina", 1],
	["Sub Jefe De Tropa Masculina", 1],
	["Jefe De Tropa Femenina", 1],
	["Sub Jefe De Tropa Femenina", 1],
	["Jefe De Clan Masculino", 1],
	["Sub Jefe De Clan Masculino", 1],
	["Jefe De Clan Femenino", 1],
	["Sub Jefe De Clan Femenino", 1],
	["Jefe De Grupo", 1],
	["Sub Jefe De Grupo", 1],
	["Tesorero De Grupo", 1],
	["Representante Institucion Patrocinadora", 1],
	["Representante de Unidad Manada Masculina", 1],
	["Representante de Unidad Manada Femenina", 1],
	["Representante de Unidad Tropa Masculina", 1],
	["Representante de Unidad Tropa Femenina", 1],
	["Representante de Unidad Clan Masculino", 1],
	["Representante de Unidad Clan Femenino", 1],
	["Comisionado Distrital", 2],
	["Asistente Distrital De Programa de Jovenes", 2],
	["Asistente Distrital De Adultos en el Movimiento", 2],
	["Asistente Distrital De Operaciones", 2],
	["Asistente Distrital De Administraccion", 2],
	["Asistente Distrital De Comunicaciones", 2],
	["Asistente Distrital De Gestion Institucional", 2],
	["Asistente Distrital De Desarrollo Financiero", 2],
	["Cooperador Distrital De Programa de Jovenes", 2],
	["Cooperador Distrital De Adultos en el Movimiento", 2],
	["Cooperador Distrital De Operaciones", 2],
	["Cooperador Distrital De Administraccion", 2],
	["Cooperador Distrital De Comunicaciones", 2],
	["Cooperador Distrital De Gestion Institucional", 2],
	["Cooperador Distrital De Desarrollo Financiero", 2],
	["Comisionado Regional", 3],
	["Asistente Regional De Programa de Jovenes", 3],
	["Asistente Regional De Adultos en el Movimiento", 3],
	["Asistente Regional De Operaciones", 3],
	["Asistente Regional De Administración", 3],
	["Asistente Regional De Comunicaciones", 3],
	["Asistente Regional De Gestion Institucional", 3],
	["Asistente Regional De Desarrollo Financiero", 3],
	["Cooperador Regional De Programa de Jovenes", 3],
	["Cooperador Regional De Adultos en el Movimiento", 3],
	["Cooperador Regional De Operaciones", 3],
	["Cooperador Regional De Administración", 3],
	["Cooperador Regional De Comunicaciones", 3],
	["Cooperador Regional De Gestion Institucional", 3],
	["Cooperador Regional De Desarrollo Financiero", 3],
	["Director Ejecutivo Nacional", 4],
	["Director Nacional De Programa de Jovenes", 4],
	["Director Nacional De Adultos en el Movimiento", 4],
	["Director Nacional De Operaciones", 4],
	["Director Nacional De Administraccion", 4],
	["Director Nacional De Comunicaciones", 4],
	["Director Nacional De Gestion Institucional", 4],
	["Director Nacional De Desarrollo Financiero", 4],
	["Coordinador Nacional De Programa de Jovenes", 4],
	["Coordinador Nacional De Adultos en el Movimiento", 4],
	["Coordinador Nacional De Operaciones", 4],
	["Coordinador Nacional De Administraccion", 4],
	["Coordinador Nacional De Comunicaciones", 4],
	["Coordinador Nacional De Gestion Institucional", 4],
	["Coordinador Nacional De Desarrollo Financiero", 4],
	["Cooperador Nacional Programa de Jovenes", 4],
	["Cooperador Nacional Adultos en el Movimiento", 4],
	["Cooperador Nacional Operaciones", 4],
	["Cooperador Nacional Administraccion", 4],
	["Cooperador Nacional Comunicaciones", 4],
	["Cooperador Nacional Gestion Institucional", 4],
	["Cooperador Nacional Desarrollo Financiero", 4],
	["Miembro del Consejo Consultivo Nacional", 4],
	["Miembro de la Corte de Honor Nacional", 4],
	["Vocal de la Corte de Honor Nacional", 4],
	["Secretario de la Corte de Honor Nacional", 4],
	["Presidente de la Corte de Honor Nacional", 4],
	["Contralor Nacional", 4],
	["Comisionado Internacional", 4],
	["Consejero Nacional", 4],
	["Tesorero Nacional", 4],
	["Sub Tesorero Nacional", 4],
	["Vice-Presidente y Sub-Jefe Scout Asociación de Scouts de Venezuela", 4],
	["Presidente y Jefe Scout Asociación de Scouts de Venezuela", 4],
	["superuser", 5]
]

p "  -> Charges: Manufacturing"
charges_list.each do |desc, stlid|
	Charge.create(description: desc, structure_level_id: stlid)
end
p "  ->   -> Created #{Charge.count} Charges"

unities_list = [
	"Manada",
	"Tropa",
	"Clan",
	"Conductor de Grupo",
	"Manada Masculina",
	"Manada Femenina",
	"Tropa Masculina",
	"Tropa Femenina",
	"Clan Masculino",
	"Clan Femenino"
]

p "  -> Unities: Manufacturing"
unities_list.each do |desc|
	Unity.create(description: desc)
end
p "  ->   -> Created #{Unity.count} Unities"

training_lev_list = [
	"Sin Nivel",
	"Nivel Básico",
	"Nivel Intermedio en Manada",
	"Nivel Intermedio en Tropa",
	"Nivel Intermedio en Clan",
	"Nivel Intermedio en Conductores de Grupo",
	"Nivel Intermedio en Institucionales",
	"Nivel Avanzado en Manada",
	"Nivel Avanzado en Tropa",
	"Nivel Avanzado en Clan",
	"Nivel Avanzado en Conductores de Grupo",
	"Nivel Avanzado en Institucionales",
	"Nivel Básico de Capacitadores",
	"Nivel Avanzado de Capacitadores",
]

p "  -> Training Levels: Manufacturing"
training_lev_list.each do |desc|
	TrainingLevel.create(description: desc)
end
p "  ->   -> Created #{TrainingLevel.count} Training Levels"

training_work_list = [
	"Curso Básico",
	"Taller de Estrategias Educativas",
	"Taller de Planificación y Programación",
	"Taller Técnico en Manada (Ambientación)",
	"Taller Técnico en Tropa (Campismo)",
	"Taller Técnico en Clan (Campismo",
	"Taller de Captación de Adultos",
	"Curso Vivencial Intermedio en Manada",
	"Curso Vivencial Intermedio en Tropa",
	"Curso Vivencial Intermedio en Clan",
	"Curso Intermedio en Cond. de Grupo e Inst.",
	"Taller de Espiritualidad",
	"Taller de Seguridad en Actividades Scout",
	"Taller de Supervisión",
	"Taller de Evaluación",
	"Taller de Manejo de Conflictos",
	"Taller LOPNA",
	"Taller ONA",
	"Curso Vivencial Avanzado en Unidades",
	"Curso Avanzado en Cond. de Grupo Inst."
]

p "  -> Training Works: Manufacturing"
training_work_list.each do |desc|
	TrainingWorkshop.create(description: desc)
end
p "  ->   -> Created #{TrainingWorkshop.count} Training Workshops"

advances_list = [
	[1, "Cachorro"],
	[1, "Huella Fresca"],
	[1, "Huella Alerta"],
	[1, "Huella Ágil"],
	[1, "Huella Libre"],
	[1, "Lobo Saltarín"],
	[2, "Novicio"],
	[2, "Aventurero"],
	[2, "Explorador"],
	[2, "Pionero"],
	[2, "Scout de Bolívar"],
	[3, "Novato"],
	[3, "Precursor"],
	[3, "Expedicionario"],
	[3, "Descubridor"],
	[3, "Fundador"],
	[3, "Rover Ciudadano"],
]

p "  -> Advances: Manufacturing"
advances_list.each do |idUnit, desc|
	Advance.create(description: desc, unity_id: idUnit)
end
p "  ->   -> Created #{Advance.count} Advances"

regions_list = [
	"Región Cero",
	"Anzoátegui",
	"Aragua",
	"Bolivar",
	"Carabobo",
	"Centro Llanos",
	"Distrito Capital",
	"Falcón",
	"Lara",
	"Merida",
	"Metropolitana",
	"Miranda",
	"Nororiental",
	"O.S.N.",
	"Táchira",
	"Zulia"
]

p "  -> Regions: Manufacturing"
regions_list.each do |desc|
	Region.create(description: desc)
end
p "  ->   -> Created #{Region.count} Regions"

districts_list = [
	[1, "DISTRITO CERO"],
	[2, "BARCELONA"],
	[2, "GUANIPA"],
	[2, "LECHERIA"],
	[2, "PUERTO LA CRUZ"],
	[2, "ZONA DE EXPANSION"],
	[3, "HENRI PITTIER"],
	[3, "JOSE FELIX RIBAS"],
	[3, "MANUEL ATANASIO GIRARDOT"],
	[3, "SANTIAGO MARIÑO"],
	[3, "SUCRE ZAMORA"],
	[4, "CARONI"],
	[4, "ORINOCO"],
	[5, "NAGUANAGUA"],
	[5, "PUERTO CABELLO"],
	[5, "SAN DIEGO"],
	[5, "VALENCIA NORTE"],
	[5, "VALENCIA SUR"],
	[5, "ZONA DE EXPANSION"],
	[6, "ACARIGUA"],
	[6, "GUANARE"],
	[6, "GUARICO"],
	[6, "YARACUY"],
	[6, "ZONA DE EXPANSION"],
	[7, "23 DE ENERO"],
	[7, "AVILA"],
	[7, "CARICUAO"],
	[7, "JOSE ANTONIO PAEZ"],
	[7, "LOS PROCERES"],
	[7, "MARISCAL SUCRE"],
	[7, "SANTIAGO DE LEON"],
	[8, "MANAURE"],
	[8, "PARAGUANA"],
	[9, "ANDRES ELOY BLANCO"],
	[9, "CATEDRAL"],
	[9, "CREPUSCULAR"],
	[9, "PALAVECINO"],
	[10, "ALBERTO ADRIANI"],
	[10, "ANDRES BELLO"],
	[10, "CARI"],
	[10, "MOCOTIES"],
	[10, "TULIO FEBRES CORDERO"],
	[11, "BARUTA"],
	[11, "CHACAO"],
	[11, "SUCRE NORTE"],
	[11, "SUCRE SUR"],
	[12, "GUAICAIPURO"],
	[12, "GUARENAS GUATIRE"],
	[12, "LOS SALIAS"],
	[12, "VALLES DEL TUY"],
	[13, "CUMANA"],
	[13, "INSULAR"],
	[14, "APURE"],
	[14, "GUARAPICHE"],
	[14, "TRUJILLO"],
	[14, "VARGAS"],
	[14, "VARYNÁ"],
	[15, "FRONTERA"],
	[15, "LUIS AMIGO"],
	[15, "PARQUE NACIONAL CHORRO EL INDIO"],
	[15, "PARQUE NACIONAL EL TAMA"],
	[15, "RIO TORBES"],
	[15, "TRASANDINO"],
	[16, "COQUIVACOA"],
	[16, "FRANCISCO POLANCO - PERIJA"],
	[16, "PEDRO HENRIQUEZ AMADO"],
	[16, "SAMUEL MARTINEZ"],
	[16, "SAN FRANCISCO"],
	[16, "ZULIA ORIENTAL"]
]

p "  -> District: Manufacturing"
districts_list.each do |idReg, desc|
	District.create(description: desc, region_id: idReg)
end
p "  ->   -> Created #{District.count} District"

groups_list = [
	[1, "GRUPO SCOUT CERO", 1],
	[2, "ARAUCA", 1],
	[2, "BROWNSEA", 1],
	[2, "DON BOSCO 17", 1],
	[2, "FRANCISCO DE MIRANDA", 1],
	[2, "JOSE ANTONIO ANZOATEGUI", 1],
	[3, "ARAGUANEY", 1],
	[3, "FRAY FERNANDO JIMENEZ", 1],
	[3, "GENESIS", 1],
	[3, "SAN MATEO - EL TIGRE", 1],
	[4, "CIVO", 1],
	[4, "DON BOSCO VII", 1],
	[5, "ANDRES ELOY BLANCO", 1],
	[5, "PADRE JOSE MARIA VELAZ", 1],
	[5, "PADRE LUIS EDUARDO GALLEGOS", 1],
	[6, "UNARE", 1],
	[7, "CIUDAD JARDIN", 1],
	[7, "HUMBOLDT", 1],
	[7, "JOSE SMITH", 1],
	[7, "LIBERTADOR", 1],
	[7, "RANCHO GRANDE", 1],
	[8, "A.L.A.S", 1],
	[8, "GUSTAVO JOSE VOLLMER H.", 1],
	[8, "MORONI", 1],
	[9, "DON BOSCO XII", 1],
	[9, "GRAN MARISCAL DE AYACUCHO", 1],
	[9, "SAN BENITO", 1],
	[9, "WEI TEPUI", 1],
	[10, "DON BOSCO", 1],
	[10, "FENIX", 1],
	[10, "GENERAL SANTIAGO MARIÑO", 1],
	[10, "INDEPENDENCIA", 1],
	[10, "ORION", 1],
	[11, "AGUSTÍN CODAZZI", 1],
	[11, "ANTONIO JOSE DE SUCRE", 1],
	[11, "EZEQUIEL ZAMORA", 1],
	[12, "KENYA", 1],
	[12, "KIM", 1],
	[12, "MORONI", 1],
	[12, "RORAIMA", 1],
	[12, "SOROCAIMA", 1],
	[13, "DON BOSCO 3", 1],
	[13, "JOSE MARIA VELAZ", 1],
	[13, "SAN FRANCISCO DE ASIS", 1],
	[13, "SIMON BOLIVAR", 1],
	[13, "TEREPAIMA", 1],
	[14, "EXPLORADORES DE BROWNSEA", 1],
	[14, "INAGUANAGOA", 1],
	[14, "NUESTRA SEÑORA DE BEGOÑA", 1],
	[14, "PIONEROS DE CARABOBO", 1],
	[15, "LA SALLE BALOCHE", 1],
	[15, "LA SALLE SAN JOSE", 1],
	[15, "SAN JORGE", 1],
	[16, "LIBERTADOR", 1],
	[16, "SAN DIEGO DE ALCALA", 1],
	[17, "ACUARIUS", 1],
	[17, "BATALLA DE CARABOBO", 1],
	[17, "CASUPO", 1],
	[17, "CONQUISTADORES DE CARABOBO", 1],
	[17, "JUPITER", 1],
	[17, "LA SALLE GUAPARO", 1],
	[18, "ALI PRIMERA", 1],
	[18, "BADEN POWELL", 1],
	[18, "CRUX", 1],
	[18, "LA SALLE HIGINIO PEDRO", 1],
	[18, "PROTINAL VALENCIA", 1],
	[19, "PADRE JORGE DEVOS", 1],
	[20, "JOHN STELZER", 1],
	[20, "TAMANACO", 1],
	[21, "GUANAGUANARE", 1],
	[22, "INDEPENDENCIA", 1],
	[22, "LOS MORROS", 1],
	[22, "TUCUNUMA", 1],
	[23, "ELIGIO VARGAS OCHOA", 1],
	[23, "NIVAR", 1],
	[23, "ROLAND ERASMUS PHILIPPS", 1],
	[24, "ACECHADORES DE MAFEKING", 1],
	[24, "GENAZARET", 1],
	[25, "CENTAUROS DE APURE", 1],
	[26, "CECILIO ACOSTA", 1],
	[26, "DINIZULU", 1],
	[26, "HORIZONTES", 1],
	[26, "MORICHE", 1],
	[26, "SAN FRANCISCO DE ASIS", 1],
	[27, "CRISTOBAL MENDOZA", 1],
	[27, "ESTOVACUY", 1],
	[27, "FLOR DE LIS", 1],
	[27, "SANTA TERESITA", 1],
	[27, "VIRGEN DE LA PAZ", 1],
	[28, "GUERREROS DE SAN MIGUEL ARCÁNGEL", 1],
	[29, "EL MARQUÉS", 1],
	[29, "RAMON IGNACIO MENDEZ", 1],
	[29, "RENACER", 1],
	[30, "ASUNCION", 1],
	[30, "JAEZULU", 1],
	[30, "SAN PEDRO CLAVER", 1],
	[31, "ARISTIDES ROJAS", 1],
	[31, "BICENTENARIO", 1],
	[31, "DON BOSCO 21", 1],
	[31, "HENRI PITTIER", 1],
	[31, "LA SALLE LA COLINA", 1],
	[31, "NEPTUNO", 1],
	[31, "PARAMACAY", 1],
	[32, "ATANASIO GIRARDOT", 1],
	[32, "CLAUDIO FELICIANO", 1],
	[32, "SAN AGUSTIN", 1],
	[32, "SAN BENITO 20", 1],
	[32, "SAN BENITO XIV", 1],
	[33, "DON BOSCO", 1],
	[33, "LAS AMERICAS", 1],
	[34, "FRANCISCO DE MIRANDA", 1],
	[34, "RORAIMA", 1],
	[35, "ALDEBARAN", 1],
	[35, "COMETA", 1],
	[35, "SAN JOSE DE CALASANZ 38", 1],
	[35, "SAN JOSE DE CALASANZ 40", 1],
	[36, "CATATUMBO", 1],
	[36, "LA SALLE TIENDA HONDA", 1],
	[36, "SAN BENITO 18", 1],
	[36, "SIMON BOLIVAR ", 1],
	[37, "DOMINGO SAVIO", 1],
	[37, "ENMANUEL", 1],
	[37, "FRANCISCO DE MIRANDA", 1],
	[38, "MATACAN", 1],
	[38, "MONTECANO", 1],
	[38, "NAZARET", 1],
	[38, "PARAGUANA", 1],
	[39, "GUERREROS DE YACAMBU", 1],
	[40, "CLARET", 1],
	[40, "GENERAL JACINTO LARA", 1],
	[40, "LA SALLE", 1],
	[40, "NUEVA SEGOVIA", 1],
	[40, "SIMON BOLIVAR", 1],
	[41, "CARLOS LAURER", 1],
	[41, "HERMANO JUAN", 1],
	[41, "MARCOS BRITO", 1],
	[41, "NUESTRA SEÑORA DEL CARMEN", 1],
	[42, "TEREPAIMA", 1],
	[43, "ALBERTO ADRIANI", 1],
	[43, "PALMARITO - LINTERNAS VERDES", 1],
	[43, "SANTA BARBARA DEL ZULIA", 1],
	[44, "JOSE FELIX RIBAS", 1],
	[44, "LA SALLE", 1],
	[44, "ORION LXXII", 1],
	[44, "SANTA BARBARA", 1],
	[44, "SANTIAGO DE LOS CABALLEROS", 1],
	[44, "UGO ANZIL", 1],
	[45, "GUAKES", 1],
	[45, "MISTAJA", 1],
	[45, "PIONEROS DE MERIDA", 1],
	[46, "INACHU", 1],
	[47, "DR. PEDRO RINCON GUTIERREZ - ULA", 1],
	[47, "JUAN FÉLIX SANCHEZ", 1],
	[47, "LIBERTADOR", 1],
	[47, "ZUHE", 1],
	[48, "AUTANA", 1],
	[48, "DIPAHO", 1],
	[48, "KURENAN", 1],
	[48, "SANTA ROSALIA DE PALERMO", 1],
	[48, "SEONEE", 1],
	[49, "FENIX", 1],
	[49, "PLEYADES", 1],
	[49, "SANTO TOMAS DE AQUINO", 1],
	[49, "TIUNA", 1],
	[50, "CLARET", 1],
	[50, "DOMINGO SAVIO", 1],
	[50, "DON BOSCO", 1],
	[50, "MACONDO", 1],
	[50, "SAN CAYETANO", 1],
	[51, "AMAZONAS", 1],
	[51, "AMAZONIA", 1],
	[51, "CACIQUE TAMANACO", 1],
	[51, "EMIRO BORDEN", 1],
	[51, "MAFEKING 100", 1],
	[51, "SIGUANOI", 1],
	[51, "WARAIRAREPANO", 1],
	[52, "DON BOSCO", 1],
	[52, "LOS NUEVOS TEQUES", 1],
	[52, "PARAMACONI", 1],
	[53, "ALFA", 1],
	[53, "ALIANZA", 1],
	[53, "EPSILON", 1],
	[53, "GAMMA", 1],
	[53, "MAFEKING100", 1],
	[53, "ORION 84", 1],
	[54, "CAYAURIMA", 1],
	[54, "MIRANDA", 1],
	[55, "CACIQUE CUE", 1],
	[55, "RAMON OCANDO PEREZ", 1],
	[56, "ANDRES ELOY BLANCO", 1],
	[56, "ANTONIO JOSE DE SUCRE", 1],
	[56, "DR. JULIAN SAUD", 1],
	[56, "G/J FRANCISCO MEJIA", 1],
	[56, "SAN FRANCISCO", 1],
	[57, "ALEJANDRO DE HUMBOLDT", 1],
	[57, "CHARAIMA", 1],
	[57, "JUAN PABLO II", 1],
	[57, "MAFEKING", 1],
	[57, "MAMPATARE", 1],
	[57, "SAN JOSE DE PARAGUACHI", 1],
	[58, "CONQUISTADORES ANDINOS", 1],
	[58, "PEDRO MARIA UREÑA", 1],
	[58, "SAN ANTONIO DE PADUA", 1],
	[59, "ASOGATA", 1],
	[59, "BROWNSEA", 1],
	[59, "CAPROU", 1],
	[59, "EDGAR ROA", 1],
	[59, "FUNTHA SIND", 1],
	[60, "BADEN POWELL XVIII", 1],
	[60, "CAPITAN MORONI", 1],
	[60, "COMUNEROS DEL TACHIRA", 1],
	[60, "FRANKLIN EDUARDO VILLAMIZAR VELAZCO", 1],
	[60, "MAFEKING", 1],
	[60, "SAN JORGE", 1],
	[61, "CIPRIANO CASTRO", 1],
	[61, "CRUZ DEL SUR", 1],
	[61, "GISA", 1],
	[61, "ROBERTO RAMIREZ G.", 1],
	[62, "ANDRES BELLO", 1],
	[62, "BADEN POWELL G.S DON BOSCO", 1],
	[62, "GUASIMOS", 1],
	[63, "JOSE MARIA VARGAS", 1],
	[63, "MEDARDA PIÑERO", 1],
	[63, "PUEBLO HONDO", 1],
	[63, "SAN JOSÉ DE BOLÍVAR", 1],
	[63, "SANTO CRISTO DE LA GRITA", 1],
	[64, "BRAVOS DE PAEZ", 1],
	[64, "INDEPENDENCIA", 1],
	[64, "LA TRINIDAD", 1],
	[64, "LUCILA PALACIOS", 1],
	[64, "PAOLA PRINCE", 1],
	[64, "SAN MARTIN DE PORRES", 1],
	[64, "SAN RAFAEL", 1],
	[65, "DON JUAN DE CHOURIO E ITURBIDE", 1],
	[65, "DR. NORIEGA TRIGO", 1],
	[65, "MARANATHA", 1],
	[66, "LOS APAMATES", 1],
	[66, "SAN JORGE", 1],
	[66, "SAN SEBASTIAN", 1],
	[66, "SAN SIMON DE BELLAS ARTES", 1],
	[67, "CAPITAN MORONI", 1],
	[67, "L.U.Z", 1],
	[67, "LA VICTORIA", 1],
	[67, "LOS OLIVOS", 1],
	[67, "RAFAEL URDANETA", 1],
	[67, "SAN PABLO", 1],
	[68, "ADRIEL ENRIQUE", 1],
	[68, "CRISTO REY", 1],
	[68, "MANAURE", 1],
	[68, "MARISCAL SUCRE", 1],
	[68, "VENEZUELA", 1],
	[69, "ALONSO DE OJEDA", 1],
	[69, "COPAIBA", 1],
	[69, "OMEGA", 1],
	[69, "PARAUTE", 1],
	[69, "SANTA RITA", 1]
]

p "  -> Scout Group: Manufacturing"
groups_list.each do |idDist, desc, parishId|
	Group.create(description: desc, district_id: idDist, parish_id: Random.rand(2...parish_list.length) )
	
end
p "  ->   -> Created #{Group.count} Scout Groups"

gender_list = ['M','F']

p "  -> People: Manufacturing

"

100.times do |index|

	first_name1 = Faker::Name.first_name
	first_name2 = Faker::Name.first_name
	last_name1 = Faker::Name.last_name
	last_name2 = Faker::Name.last_name


	spr1 = SprPerson.create(document: (1000000 + Random.rand(999999)), 
					 asv_member: Faker::Boolean.boolean,
					 representative: Faker::Boolean.boolean, 
					 first_name: first_name1, 
					 second_name: first_name2, 
					 first_last_name: last_name1, 
					 second_last_name: last_name2, 
					 gender: gender_list[Random.rand(0...1)], 
					 mobile_phone: "0414-"+Random.rand(2312311...9999999).to_s, 
					 phone: "0"+Random.rand(241...281).to_s+"-"+Random.rand(2312311...9999999).to_s,
					 main_email: Faker::Internet.email(first_name1 + "." + last_name1+"#{index}"),
					 second_email: Faker::Internet.email(first_name1 + "." + last_name1+"#{index}"),
					 relationship_id: Random.rand(1...relationship_list.length),
					 ocupation_id: Random.rand(1...ocp_list.length),
					 nationality_id: Random.rand(1...nationality_list.length),
					 document_type_id: Random.rand(1...document_type_list.length),
					 academic_level_id: Random.rand(1...academic_lev_list.length),
					 address: Faker::Address.full_address)

	pr1 = Person.create(dnis: Random.rand(4356...13000),
				  spr_person_id: spr1.id,
				  birth: Faker::Time.between(80.years.ago, 21.years.ago),
				  promise_day: Faker::Time.between(70.years.ago, 1.week.ago),
				  parish_id: Random.rand(1...parish_list.length) )


	flag = Faker::Boolean.boolean;
	
	prc1 = 0;
		if flag
			if SprPerson.count>1
				prc1 = ProgramReceptor.create(person_id: pr1.id,
									      spr_person_id: Random.rand(1...SprPerson.count))
				Registry.create( program_receptor_id: prc1.id,
				 			 registry_date: Faker::Time.between(1.year.ago, 1.week.ago),
				 			 group_id:  Random.rand(2...groups_list.length),
							 unity_id: Random.rand(1...unities_list.length),
							 charge_id: Random.rand(1...23)
				 			 )		
			else
				Registry.create( person_id: pr1.id,
			 			 registry_date: Faker::Time.between(1.year.ago, 1.week.ago),
			 			 group_id:  Random.rand(2...groups_list.length),
						 unity_id: Random.rand(1...unities_list.length),
						 charge_id: Random.rand(1...23)
			 			 )	
			end
			

		else
			Registry.create( person_id: pr1.id,
			 			 registry_date: Faker::Time.between(1.year.ago, 1.week.ago),
			 			 group_id:  Random.rand(2...groups_list.length),
						 unity_id: Random.rand(1...unities_list.length),
						 charge_id: Random.rand(1...23)
			 			 )
		end


	

	
end

p "  -> Created #{SprPerson.count} Instances of People..."
p "  ->   -> #{Person.count - ProgramReceptor.count} Instances of Scout Adults..."
p "  ->   -> #{ProgramReceptor.count} Instances of Program Receptors..."
p "Created #{Registry.count} Registries..."



p "


.................that's all... yay! :)"